version: '3.8'
services:
  app:
    container_name: kniitnon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PRISMA_URL=postgresql://postgres:podcastuser@db:5432/kniitnon
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=podcastuser
      - POSTGRES_DB=kniitnon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: