name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    
    - name: Run database migrations
      run: |
        cd backend
        alembic upgrade head
    
    - name: Start backend server
      run: |
        cd backend
        python run_server.py &
        sleep 5
    
    - name: Run smoke tests
      run: |
        node scripts/smoke-test.js
    
    - name: Run backend tests
      run: |
        cd backend
        python -m pytest
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm test -- --run
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
