name: Deploy to Cloud Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: kniitnon
  GAR_LOCATION: us-central1
  SERVICE: kniitnon
  REGION: us-central1

jobs:
  deploy:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: |-
          gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA" .
          docker push "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
